spring:
  application:
    name: transaction-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
      - com.google.cloud.spring.autoconfigure.spanner.SpannerTransactionManagerAutoConfiguration
  cloud:
    gcp:
      project-id: test-project
      spanner:
        project-id: test-project
        instance-id: test-instance
        database: test-database
        min-sessions: 0
        max-sessions: 5
        fail-if-invalid-session: false
        emulator:
          enabled: true
  devtools:
    restart:
      enabled: false
      exclude: com/example/transaction_service/model/**,com/example/transaction_service/workflow/**
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 9090
  address: 0.0.0.0
  http2:
    enabled: true

restate:
  sdk:
    http:
      port: 9091
  client:
    base-uri: http://localhost:8080

accounts:
  service:
    url: http://localhost:7070

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}