@startuml high-level-diagram
left to right direction
skinparam componentStyle rectangle

' =========================
' Microservices Level
' =========================
package "Microservices Level" {
  component "app1" as app1
  component "app2" as app2
  component "app3" as app3

  component "<size:20><&book>App Log 1<&book></size>" as appLog1 #LightCoral
  component "<size:20><&book>App Log 2<&book></size>" as appLog2 #LightCoral
  component "<size:20><&book>App Log 3<&book></size>" as appLog3 #LightCoral

  
}

' =========================
' Durable Workflows Level
' =========================
package "Durable Workflows Level" {
  component "Durable Workflows\nEngine" as temporal #LightCoral
}

' =========================
' Database Level
' =========================
package "Database Level" as dbLevel{
  database "db1\nPostgres" as db1
  database "db2\nPostgres" as db2
  database "db3\nSpanner" as db3

  component "<size:20><&book>DB Log 1<&book></size>" as dbLog1 #MediumAquaMarine
  component "<size:20><&book>DB Log 2<&book></size>" as dbLog2 #MediumAquaMarine
  component "<size:20><&book>DB Log 3<&book></size>" as dbLog3 #MediumAquaMarine
}

' =========================
' Messaging Level
' =========================
package "Messaging Level" {
  queue "Message Broker" as kafka
}

' =========================
' CDC Level
' =========================
package "CDC Level" {
  component "CDC Connector" as cdcConnector #MediumAquaMarine
}

component "Drift Detector" as driftDetector

' =========================
' External Consumers
' =========================
component "BigQuery" as bigquery
component "Other Listeners" as listeners

' =========================
' Observability
' =========================
' package "Observability Level" {
'   component "Dashboards" as dashboards
'   component "Logs" as logs
'   component "Metrics" as metrics
' }

' =========================
' App -> DurableState writes
' =========================

app1 --> appLog1
app2 --> appLog2
app3 --> appLog3

' =========================
' App -> DB writes
' =========================
temporal --> db1
temporal --> db2
temporal --> db3


' =========================
' DB -> Log writes
' =========================
db1 --> dbLog1
db2 --> dbLog2
db3 --> dbLog3

' =========================
' CDC reads DB changes
' =========================
dbLog1 --> cdcConnector
dbLog2 --> cdcConnector
dbLog3 --> cdcConnector


' =========================
' Drift Detector Accepts events
' =========================
driftDetector --> cdcConnector
driftDetector --> bigquery

' =========================
' CDC -> Kafka
' =========================
cdcConnector --> kafka
' cdcConnector --> kafka
' cdcConnector --> kafka

' =========================
' Kafka -> Consumers
' =========================
kafka --> bigquery
kafka --> listeners

' =========================
' Workflow -> Apps
' =========================
temporal <-- appLog1
temporal <-- appLog2
temporal <-- appLog3

@enduml