@startuml high-level-diagram
top to bottom direction
skinparam componentStyle rectangle

' =========================
' Microservices Level
' =========================
package "Microservices Level" {
  component "transactions" as app1
  component "accounts" as app2
  
}

' =========================
' Durable Workflows Level
' =========================
package "Durable Workflows Level" {
  component "Restate" as restate #LightCoral
}

' =========================
' Database Level
' =========================
package "Database Level" {
  database "db1\nSpanner" as db1
  database "db2\nPostgres" as db2

  component "<size:10><&book>DB Log 1<&book></size>" as dbLog1 #MediumAquaMarine
  component "<size:10><&book>DB Log 2<&book></size>" as dbLog2 #MediumAquaMarine
}

' =========================
' Messaging Level
' =========================
package "Messaging Level" {
  queue "Kafka\nMessage Broker" as kafka
}

' =========================
' CDC Level
' =========================
package "CDC Level" {
'   component "DB\nConnector1" as debez1
'   component "DB\nConnector2" as debez2
'   component "DB\nConnector3" as spannerCDC
  component "Debezium" as cdcConnector #MediumAquaMarine
  
}

component "Drift Detector" as driftDetector #MediumAquaMarine

' =========================
' External Consumers
' =========================
component "Other Listeners" as listeners

' =========================
' Observability
' =========================
' package "Observability Level" {
'   component "Dashboards" as dashboards
'   component "Logs" as logs
'   component "Metrics" as metrics
' }

' =========================
' App -> DB writes
' =========================
app1 --> db1 : (2)
app2 --> db2 : (2)


' =========================
' DB -> Log writes
' =========================
db1 --> dbLog1
db2 --> dbLog2

' =========================
' CDC reads DB changes
' =========================
dbLog1 --> cdcConnector : (3)
dbLog2 --> cdcConnector : (3)


' ' =========================
' ' Drift Detector Accepts events
' ' =========================
' driftDetector --> cdcConnector
' driftDetector --> listeners

' =========================
' CDC -> Kafka
' =========================
cdcConnector --> kafka : (4)
cdcConnector --> kafka : (4)

' =========================
' Kafka -> Consumers
' =========================
kafka ..> listeners : (5)
kafka ..> driftDetector : (5)

' =========================
' Workflow -> Apps
' =========================
restate ..> app1 : (1)
restate ..> app2 : (1)

' note top of restate
' Tasked with synchronous
' communication between apps
' end note

@enduml