@startuml test
left to right direction
skinparam componentStyle rectangle
skinparam shadowing false

actor Client

package "Spring Boot / JPA Services" {

  component "Account Service\n<<aggregate>> Account" as ACCT {
    [Event Publisher] as ACCT_EP
    [Event Handler] as ACCT_EH
    [JPA] as ACCT_JPA
  }

  component "Transaction Service\n<<aggregate>> Transaction" as TRNSC {
    [Event Publisher] as TRNSC_EP
    [Event Handler] as TRNSC_EH
    [JPA] as TRNSC_JPA
  }

  ' ' alternative: replace with bigquery to emulate reconciliation
  ' component "Transaction History Service" as OHS {
  '   [Event Handler] as THS_EH
  '   [CQRS Writer] as OHS_CQRS
  ' }
}

package "BigQuery" {
  database "BigQuery" as BQ {
    
  }
  component "Event Handler" as THS_EH
}

package "PostgreSQL" {

  database "ACCOUNT table" as DB_ACCOUNT {
    [ID]
    [AMOUNT]
  }

  database "MESSAGE table\n(Outbox)" as DB_MESSAGE_PS {
    [ID]
    [DESTINATION]
  }

  collections "Write Ahead Log" as WAL
}

package "Spanner"{

    database "TRANSACTION table" as DB_TRANSACTION {
        [ID]
        [ACCOUNT_ID]
        [TRANSACTION_TOTAL]
    }

    database "MESSAGE table\n(Outbox)" as DB_MESSAGE_SP {
    [ID]
    [DESTINATION]
  }

    collections "Spanner Change Streams" as SPANNER_CS


}

package "Apache Kafka" {
  queue "Account topic" as K_ACCOUNT
  queue "Transaction topic" as K_TRANSACTION
}

package "Debezium"{
  component "Debezium PostgreSQL\nCDC Service" as PS_CDC
  component "Debezium Spanner\nCDC Service" as SP_CDC
}

' =====================
' REST endpoints
' =====================

Client --> ACCT : POST /account
Client --> TRNSC : POST /transactions\nGET /transactions/{transactionId}
' Client --> OHS : GET /account/{accountId}\nGET /transactions/{transactionId}

' =====================
' Account Service flow
' =====================

ACCT --> ACCT_JPA
ACCT_JPA --> DB_ACCOUNT : update

ACCT_EP --> DB_MESSAGE_PS : publish events
ACCT_EH ...[#0000FF]> K_TRANSACTION : subscribes to

' =====================
' Transaction Service flow
' =====================

TRNSC --> TRNSC_JPA
TRNSC_JPA --> DB_TRANSACTION : update

TRNSC_EP --> DB_MESSAGE_SP : publish events
TRNSC_EH ...[#0000FF]> K_ACCOUNT : subscribes to

' =====================
' Outbox + CDC
' =====================

DB_ACCOUNT --> WAL
DB_TRANSACTION --> SPANNER_CS
DB_MESSAGE_PS --> WAL
DB_MESSAGE_SP --> SPANNER_CS

SP_CDC -[#red]> SPANNER_CS : <font color=red>reads from
SP_CDC ..> K_TRANSACTION : publishes to

PS_CDC -[#red]> WAL : <font color=red>reads from
PS_CDC ..> K_ACCOUNT : publishes to


' =====================
' Transaction History Service
' =====================

THS_EH ...[#0000FF]> K_ACCOUNT : subscribes to
THS_EH ...[#0000FF]> K_TRANSACTION : subscribes to
THS_EH --> BQ : pushes to
' OHS_CQRS --> MONGO : update CQRS view

' =====================
' Notes
' =====================

note bottom of ACCT
ACID transaction:
- Update DB
- Publish events (outbox)
end note

note bottom of TRNSC
ACID transaction:
- Update DB
- Publish events (outbox)
end note

@enduml
